# Generated by Django 4.1.3 on 2022-11-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_delete_currentloc'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='SubscriptionPlan',
        ),
    ]
