# Generated by Django 4.1.3 on 2022-11-16 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0004_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
