# Generated by Django 4.1.3 on 2022-11-16 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0007_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='user',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
