# Generated by Django 4.1.3 on 2022-11-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscriptionplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='user',
        ),
    ]
