# Generated by Django 4.1.3 on 2022-11-16 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='next_billing_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
