# Generated by Django 4.1.3 on 2022-11-16 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_rename_billing_date_userpaymenthistory_billing_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
