# Generated by Django 4.1.3 on 2022-11-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_userpaymenthistory_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='studio',
        ),
    ]
