# Generated by Django 4.1.3 on 2022-11-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_remove_subscriptionplan_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=10),
        ),
    ]
