# Generated by Django 4.1.3 on 2022-11-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.OneToOneField(error_messages={'unique': 'Users can only subscribe to one plan. Please use updateAPI if you want.'}, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
    ]
