# Generated by Django 4.1.3 on 2022-11-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_alter_usersubscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
