# Generated by Django 4.1.3 on 2022-11-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_usersubscription_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='start_date',
        ),
    ]
