# Generated by Django 4.1.3 on 2022-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0027_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
