# Generated by Django 4.1.3 on 2022-11-12 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(max_length=400)),
                ('location', models.CharField(help_text='latitude, longitude. e.g. 43.66, -79.39', max_length=13, validators=[django.core.validators.RegexValidator(message='Please follow this example format: (xx.xx, xx.xx)', regex='^[1-9][0-9].[0-9]{2}, -?[1-9][0-9].[0-9]{2}$')])),
                ('postal_code', models.CharField(help_text='e.g. M0S3C4', max_length=6, validators=[django.core.validators.RegexValidator(message='Please follow this example format: M0S3C4', regex='^[A-Za-z]\\d[A-Za-z]\\d[A-Za-z]\\d$')])),
                ('phone_number', models.CharField(help_text='e.g. 123-123-1234', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'xxx-xxx-xxxx'.", regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studio/')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='type')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='studios.studio')),
            ],
        ),
    ]
