# Generated by Django 4.1.3 on 2022-11-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_currentlocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentLocation',
            new_name='CurrentLoc',
        ),
    ]
