# Generated by Django 4.1.3 on 2022-11-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_rename_currentlocation_currentloc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentLoc',
        ),
    ]
