# Generated by Django 4.1.3 on 2022-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_remove_studio_location_studio_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
