# Generated by Django 4.1.3 on 2022-11-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_currentloc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentLoc',
        ),
    ]
