# Generated by Django 4.1.3 on 2022-11-17 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studios', '0007_delete_currentloc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseKlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=400)),
                ('coach', models.CharField(max_length=200)),
                ('keywords', models.TextField(blank=True, max_length=400)),
                ('capacity', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_klass', to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='KlassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base_klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klass_instance', to='classes.baseklass')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.klassinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
