# Generated by Django 4.1.3 on 2022-11-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_baseklass_options_alter_klassinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseklass',
            name='add_all',
            field=models.BooleanField(default=False, help_text='Choose if you want to add all class instances between start, end date'),
        ),
    ]
