# Generated by Django 4.1.3 on 2022-11-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_add_all_baseklass_add_all_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseklass',
            name='add_all_instances',
        ),
    ]
