# Generated by Django 4.1.3 on 2022-11-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_cancelledklassinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelledklassinstance',
            options={'verbose_name': 'Cancelled Class instance', 'verbose_name_plural': 'Cancelled Class instances'},
        ),
    ]
