# Generated by Django 4.1.3 on 2022-11-17 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='e.g. 123-123-1234', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'xxx-xxx-xxxx'.", regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
    ]
